name: Frontend - Build & Deploy

on:
  push:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm run test

      - name: Run linting
        run: |
          cd frontend
          npm run lint

      - name: Build Vite App
        run: |
          cd frontend
          npm run build

  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend
        run: echo "Deploying frontend from main..."
